name: Fetch Rancher Offline Image (Chunked)
on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Official Rancher Image
        run: docker pull rancher/rancher:latest

      - name: Save Image to Tarball
        run: docker save -o rancher-server.tar rancher/rancher:latest

      - name: Encode and Split into 500MB Chunks
        run: |
          mkdir output_folder
          base64 rancher-server.tar | split -b 500m - output_folder/rancher_part_
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rancher-chunks
          path: output_folder/
