#rancher
name: Fetch Rancher Offline Image (Encoded)
on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Official Rancher Image
        run: docker pull rancher/rancher:latest

      - name: Save Image to Tarball
        run: docker save -o rancher-server.tar rancher/rancher:latest

      - name: Encode to Base64 Text
        run: |
          mkdir output_folder
          base64 rancher-server.tar > output_folder/rancher-server.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rancher-offline-text
          path: output_folder/
