name: Build and Export Zork Container
on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # <-- UPDATED to v4

      - name: Build the Docker Image
        run: docker build -t zork-jail:v1 .

      - name: Save Image to Tarball
        run: docker save -o zork-jail.tar zork-jail:v1

      - name: Save Image to Tarball
        run: docker save -o zork-jail.tar zork-jail:v1

      - name: Encode Tarball to Base64 Text
        run: base64 zork-jail.tar > zork-jail.txt
